spring:
  application:
    name: unit-test-with-spring

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unit_tests
    username: rory
    password: rootroot

